language: c
sudo: false

# Blacklist
#branches:
#  except:
#    - gh-pages

env:
  global:
     - PRETTYNAME="DLogNet"

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.8.5-linux64.tar.xz
  - tar xf arduino-1.8.5-linux64.tar.xz
  - sudo mv arduino-1.8.5 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino

install:
  - ln -s $PWD /usr/local/share/arduino/libraries/DLog
  - arduino --pref "compiler.warning_level=all" --save-prefs
# install esp8266
  - arduino --pref "boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json" --save-prefs
  - arduino --install-boards esp8266:esp8266
# install esp32
  - pushd .
  - mkdir -p ~/Arduino/hardware/espressif
  - cd ~/Arduino/hardware/espressif
  - git clone https://github.com/espressif/arduino-esp32.git esp32
  - cd esp32
  - git submodule update --init --recursive
  - cd tools
  - python2 get.py
  - mkdir -p ~/Arduino/libraries
  - cd ~/Arduino/libraries
  - git clone  https://github.com/liebman/DLog.git
  - popd
  
script:
  - "echo $PWD"
  - "echo $HOME"
  - "ls $PWD"
  - source $TRAVIS_BUILD_DIR/travis/common.sh
  - arduino --board esp8266:esp8266:generic:CpuFrequency=80,CrystalFreq=26,FlashFreq=40,FlashMode=qio,FlashSize=4M1M,led=2,LwIPVariant=v2mss536,Debug=Serial,DebugLevel=CORE --save-prefs
  - build_examples
  - arduino --board espressif:esp32:esp32:FlashMode=qio,FlashFreq=80,FlashSize=4M,DebugLevel=info --save-prefs
  - build_examples

#after_success:
#  - bash <(curl -s https://codecov.io/bash)
